# TOKEN = '6787855008:AAFNpFZ-Y1DD_x1mV0UYoPqH0AVwTW9iacQ'
TOKEN = '5924781016:AAFe6DmVlFmhFGWE18Y-wSfFN6gcHzrh3Zk'
GPT_URL = 'http://localhost:1234/v1/chat/completions'
MODEL_URI = ''
IAM_TOKEN = ''
FOLDER_ID = 'b1gr1l4ru3gbjel7ihgi'
HEADERS = {"Content-Type": "application/json"}
MAX_TOKENS = 100
MAX_LETTERS = 100
SUBJECTS = ['biology', 'math', 'russian']
LEVELS = ['beginer', 'advanced']
SYSTEM_CONTENT = ''
ASSISTANT_CONTENT = 'Решим задачу по шагам:'
MODEL_NAME = "mistralai_mistral-7b-instruct-v0.1"
DB_NAME = 'db.sqlite'
